### ISSUE TITLE
Cart, Session and User

### ISSUE THREAD

**Issue by Geurney** [scalableinternetservices/fastbuy#16]
Currently we create a cart when clicking the AddToCart button if there is no cart initially. If we close the browser and reopen it again, it will create another cart when clicking the AddToCart button. At this time, we can browse the first cart with  carts/1 URL and browse all the carts  with carts/index URL. 

In a session, when we create a cart, we insert a cart record into the Cart Table in database and by using @carts = Cart.all statement, we can get all the records in the Cart Table. And we can also browse individual cart by visiting carts/# to fetch a specific record.

But now we want customer A only to see his own cart, not others. So we introduce user authorization. This authorization can enforce a user to sign in / sign up before he can add items to his cart. However, this doesn't prevent him from browsing other carts. 

This is because the user authorization now only ensures there is a signed in user in the current session, it fails to associate itself with a particular cart. In order to solve this problem, we have to assign each user a unique cart. This means in the User Table, there should be a cart_id attribute.And the procedure should go as follows:
1. Ask the user to sign in.
2. Find the cart_id based on the user_id
3. Get the cart based on the cart_id
4. Edit/View item in the cart.

**Comment by Geurney** [comment]
In a nutshell, instead of getting the cart by looking in session[:cart], we should get the cart with current_user.cart_id.

**Comment by aacalfa** [comment]
Fixed by commit 693bcfdfde6e6ce739a65bb90da31876b81408c3. Closing the issue
